- .github/workflows/hari-client-pytest.yaml
- .github/workflows/pre-commit-test.yaml
- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- setup.py
- Changed minimum python version to 3.11, due to the features used in https://github.com/quality-match/hari-client/pull/1
- Added github actions workflow for running pytest tests when creating a PR towards `main`
- Link Changelog in Readme
- Explain development setup in Readme
> Package maintenance and pytest workflow

- hari_client/client/client.py
- hari_client/models/models.py
- tests/test_client.py
- tests/test_parse_response_model.py
Response parser is quite complex. Returning lists, unions or other custom types is confusing.
- [Allow extra attributes in responses](https://github.com/quality-match/hari-client/commit/3cc6ec7eb765b43b4f88f3832fa195ee11bb4dcf)
- added this to any type that looked like it was used for parsing responses to add this information for the user. So far, it was ignored
- [Add models for endpoints returning lists](https://github.com/quality-match/hari-client/commit/13ddb514cfe0f5ef9511268523a8427b281c87fb)
- add models inheriting from pydantic.Rootmodel to make response parsing easier
- [Update parsing of response models](https://github.com/quality-match/hari-client/commit/b6182b447efb3786315acc93902ea7770f5910ea)
- make response parsing easier
- [Update create_subset-method to reflect …
> Use proper pydantic models for response parsing

- hari_client/client/client.py
- hari_client/models/models.py
- tests/test_parse_response_model.py
This reverts the changes made in PR #11 `Use proper pydantic models for response parsing`
This reverts commit 6ff5d221e175343648c38054bc46e1c9c20d598c, reversing changes made to 57f064f568cadbe76779a6bd16bdd43eb2853c7a.
- we received a report of failed response parsing. Checking out an earlier commit 3cc6ec7eb765b43b4f88f3832fa195ee11bb4dcf fixed the issue for the dev.
- The changes of this PR that aren't related to the refactoring of the response parsing logic will be reapplied in a new PR
> Revert PR#11

- CHANGELOG.md
- hari_client/client/client.py
- hari_client/models/models.py
- tests/test_parse_response_model.py
Review and merge only after PR #13 is merged.
This PR reapplies some changes from the reverted PR#11:
- update create_subset method
- allow extra fields in api models
There's also one additional cleanup:
- commit 2818e2b40b29b180e06a920b29b59a617a91e230 removes a workaround from the response parsing logic which was introduced in v0.1.0, when it wasn't possible to explicitly define `list[MyModel]` as the response type. This has been enabled by PR #1 though. See changelog for more details and overview
> Reapply pr #11 partially

- CHANGELOG.md
- docs/example_code/quickstart.py
- hari_client/client/client.py
- hari_client/client/errors.py
- hari_client/models/models.py
- tests/test_client.py
- tests/test_models.py
- tests/test_parse_response_model.py
1610400640
This PR adds compatibility updates for HARI backend version 7.0.3.
- added support for new metadata rebuild endpoints. One method is enough to trigger all necessary metadata update prcessing jobs
- updated the quickstart example code to use the new hari_uploader interface and the new metadata rebuild endpoint
- renamed field `customer` of Dataset model and create_dataset endpoint to `user_group`
- added new error classes: `ParameterNumberRangeError` and `ParameterListLengthError`
- the api response model for the processing jobs changed from unions of specific models to only being a generic model
> Compatibility updates for hari v7.0.3

- CHANGELOG.md
- README.md
- docs/example_code/quickstart.py
- hari_client/client/client.py
- hari_client/models/models.py
- hari_client/upload/hari_uploader.py
- setup.py
- tests/test_hari_uploader.py
- Back references aren't required to be unique anymore. Empty and duplicate back_references will log a warning though
- Back references aren't used in the bulk media and media_object upload endpoints anymore. Instead a randomly generated and temporary bulk_operation_annotatable_id is used
- Update quickstart script to fetch processing jobs via trace_id
> Update hari uploader interface to use bulk_operation_annotatable_id

- CHANGELOG.md
- hari_client/upload/hari_uploader.py
- tests/test_hari_uploader.py
When a media object for media or an attribute for media/media object is shared, this shared attribute/object for different media/media object is updated all the times that any of the attributes is updated, so at the end all attributes that were shared receive the last media/annotatable id and it created duplicated attribute (with the same attribute id and annotatable id)
The pr update fixes the issue
> fix shared media object/attribute correct media/annotatable id update

- CHANGELOG.md
- hari_client/client/client.py
- hari_client/models/models.py
The hari API no longer allows the object_category to be arbitrary strings, but it rather has to be a UUID.
This PR adjusts the client to match this behavior and adds a custom JSONEncoder, that is able to serialize UUIDs.
> Restrict object_category field to UUID

- CHANGELOG.md
- docs/example_code/quickstart.py
- hari_client/models/models.py
- hari_client/upload/hari_uploader.py
- setup.py
- tests/conftest.py
- tests/test_client.py
- tests/test_hari_uploader.py
- tests/upload/fixtures.py
1648824166
Users should be able to specify object categories and directly translate them into HARI as subsets.
This PR introduces this functionality
- adds utility-methods to the `HariUploader` used by the `upload`-method
- _create_object_category_subsets
- _validate_media_objects_object_category_subsets_consistency
- _assign_media_objects_to_object_category_subsets
- updates `quickstart.py`
- updates integration tests with object categories
- adds unit tests
> Setup of object category subsets in hari uploader

- docs/example_code/quickstart.py
- hari_client/models/models.py
- hari_client/upload/hari_uploader.py
- tests/test_hari_uploader.py
1648824166
The inconsistencies weren't really a technical problem, because we now have the custom UUID serializer from #29, but there were pydantic warnings about it when running the quickstart script. They should be gone now with this update.
> Clean up of uuid vs str inconsistencies in current client api models

- hari_client/client/client.py
the question field gets special treatment in the backend, therefore it must be ignored by the client if it's None
> fix `HARIClient.create_attribute` method

- CHANGELOG.md
- README.md
- hari_client/client/client.py
- hari_client/upload/hari_uploader.py
- setup.py
- tests/upload/fixtures.py
Hari has multiple endpoints for creating subsets.
The one we were using so far contains more logic and takes longer to execute. The extra logic is already covered in metadata_rebuild, which is necessary to be called, anways.
> Make use of empty subset creation endpoint

- CHANGELOG.md
- README.md
- hari_client/client/client.py
- setup.py
1614747154
Without this fix the serialization of datetime objects fails, because it's not handled automatically.
> Serialize datetime objects to iso 8601 strings

- CHANGELOG.md
- hari_client/client/client.py
Adds a flag for metadata rebuilding, crop and thumbnail creation, that forces the recreation of existing thumbnails and crops. This flag is only available to internal users.
> Add force_recreate flag

- CHANGELOG.md
- README.md
- setup.py
Release 2.1.0
- added support for `anonymize` and `calculate_histograms` parameters to `trigger_metadata_rebuild_job` and `trigger_dataset_metadata_rebuild_job`
- added support for `force_recreate` flag for these methods:
- `trigger_crops_creation_job`
- `trigger_thumbnails_creation_job`
- `trigger_dataset_metadata_rebuild_job`
- `trigger_metadata_rebuild_job`
> Release 2.1.0

- CHANGELOG.md
- hari_client/models/models.py
Add repeats and possible values, as well as cant solve ration, to all attribute models
> Add repeats, possible values and cant solve ratio to all attribute models

- CHANGELOG.md
- docs/example_code/quickstart.py
- docs/example_code/upload_new_data_to_existing_dataset/upload_new_data_to_existing_dataset.py
- hari_client/client/client.py
- tests/test_client.py
1721653103
The `query` argument wasn't serialized properly for multiple methods.
This is now fixed. Support for existing workarounds, where the query argument was passed as an already stringified single QueryParameter oder LogicParameter object or as a list of those is kept, but will be removed in the future. If you've already used this workaround, please update your scripts.
> Fix query arg serialization

- CHANGELOG.md
- hari_client/client/client.py
- tests/test_client.py
1739954130
Fixes a bug introduced in #42 (not included in any release).
Mixed file extensions led to mixing up the mapping between uploaded image files and medias.
> Fix mixed media file extensions upload

- CHANGELOG.md
- hari_client/__init__.py
- hari_client/client/errors.py
- hari_client/models/models.py
- hari_client/models/validation/__init__.py
- hari_client/models/validation/attribute_validation.py
- hari_client/upload/hari_uploader.py
- tests/test_attribute_validations.py
- tests/test_parse_response_model.py
the validation is run automatically when using the hari_uploader's upload method.
Per default the validation is also run in the client's create_attributes method, but can be disabled with an arg, which the hari_uploader uses to prevent validation from running again for every batch.
Also took the opportunity to set the annotatable_type of attributes in the hari_uploader before the upload happens. Knowing the annotatable type is important for the validation.
> add validations for initial attributes

- CHANGELOG.md
- hari_client/client/client.py
We changed the way thumbnails and crops are created in the backend. As a result, the API-endpoints
- /datasets/{dataset_id}/thumbnails
- /datasets/{dataset_id}/crops
were removed
Remove `trigger_thumbnails_creation_job` and `trigger_crops_creation_job`
https://quality-match.monday.com/boards/1606259534/pulses/1797705485
> Remove client methods for obsolete api endpoints

- CHANGELOG.md
- hari_client/client/client.py
- hari_client/models/models.py
Using release branch to align the client release with its changes in the API
- /datasets/{dataset_id}/thumbnails
- /datasets/{dataset_id}/crops
were removed in the API
- possible values for attributes are restricted to be a list of strings
This needs to be released after these changes are live in the API
Remove trigger_thumbnails_creation_job and trigger_crops_creation_job
https://quality-match.monday.com/boards/1606259534/pulses/1797705485
> Release 4.0.0

- CHANGELOG.md
- hari_client/client/client.py
- hari_client/client/errors.py
- hari_client/models/models.py
- hari_client/upload/hari_uploader.py
- tests/conftest.py
- tests/test_client.py
- tests/test_hari_uploader.py
- tests/upload/fixtures.py
1777395874
add support for skipping media file upload in create_medias and hari_uploader when all medias have a set media_url. HARIMedia validates whether the set media_url is valid as a url for an media in a dataset that uses an external media source
> hari-client and hari_uploader utility update for supporting external media sources

- CHANGELOG.md
- hari_client/config/config.py
As the primary HARI API domain was replaced by "api.hari.quality-match.com", we should set this as the new default.
Note that the old domain is still supported for some time to maintain compatibility.
> replace hari_api_base_url default with new api domain

- hari_client/client/client.py
Changes:
The api now requires a limit to be set. To keep the client behavior alive we have done the following:
- add get_*_paginated functions for all entities in the client
- call get_*_paginated in list endpoint calls that are called with limit = None
[Task](https://quality-match.monday.com/boards/1606259534/pulses/2054145430)
> adjust client for default limit adjustments
