quality-match/hari-client

README.md, docs/example_code/geometries.py, docs/example_code/quickstart.py, hari_client/client/client.py, hari_client/models/models.py
Update quickstart script with checking thumbnails creation status before triggering crops creation
=> Update example with status tracking

docs/example_code/quickstart.py, hari_client/client/client.py
Wait for thumbnails creation job to be started in a loop
=> Improve quickstart example

docs/example_code/quickstart.py, hari_client/client/client.py, hari_client/client/errors.py, hari_client/models/models.py, hari_client/upload/hari_uploader.py, tests/test_parse_response_model.py
- Update code with 3.11 syntax:
-remove type in args section of docstring
- replace typing.Optional with pipe
- replace typing.Union with pipe
-
- Improve quickstart example
- Remove linter errors in quickstart
=> Km/hari client/apply feedback

CHANGELOG.md, docs/example_code/quickstart.py, hari_client/upload/hari_uploader.py, tests/test_hari_uploader.py
fixed merge_bulk_responses for the case when no responses are given
=> Fix merge bulk responses bug

hari_client/upload/hari_uploader.py
Fix upload bug when there are no media objects
=> Fix upload bug when there are no media objects

CHANGELOG.md, docs/example_code/quickstart.py, hari_client/client/client.py, hari_client/models/models.py, hari_client/upload/hari_uploader.py, tests/test_hari_uploader.py
This adds the ability to upload attributes to the HARI client.
Additional changes:
- some linting
=> add attribute upload

CHANGELOG.md, hari_client/client/client.py, hari_client/models/models.py
Adds CRUD methods for attributes to the client.
=> CRUD methods for attributes

docs/example_code/quickstart.py, hari_client/client/client.py, hari_client/models/models.py
Make attribute group optional defaulting to initial when creating attribute(s)
=> Make attribute group optional defaulting to initial

CHANGELOG.md, docs/example_code/quickstart.py, hari_client/client/client.py, hari_client/models/models.py
Make media object source optional defaulting to reference during media object creation
=> Make media object source optional defaulting to reference

hari_client/models/models.py, tests/test_hari_uploader.py
Revert id of AttributeCreate back to string
=> Revert id of AttributeCreate back to string

CHANGELOG.md, hari_client/client/client.py, hari_client/models/models.py
1669420302
Background
restrict annotatable type
restrict updating some attribute fields
=> Restrict attribute models

hari_client/client/client.py
Request errored out because server expected different model.
Fix update_attribute-method
=> Fix update attribute request

CHANGELOG.md, hari_client/client/client.py, hari_client/client/errors.py, hari_client/models/models.py, hari_client/upload/hari_uploader.py, tests/test_models.py
Add bulk operation annotatable id validation for bulk media and objects creation models
=> Add bulk operation annotatable id validation for bulk media and objects creation models

CHANGELOG.md, hari_client/upload/hari_uploader.py, tests/test_hari_uploader.py, tests/upload/fixtures.py
include existing attributes when validating the number of attributes
=> include existing attributes when validating the number of attributes

CHANGELOG.md, hari_client/client/client.py, hari_client/models/models.py
1795640538
Restrict attribute possible_values to be a list of strings
=> Restrict attribute possible_values to be a list of strings

CHANGELOG.md, hari_client/client/client.py
Update get datasets method with pagination and query, add get dataset count method
=> Update get datasets method with pagination and query, add get dataset count method

CHANGELOG.md, hari_client/client/client.py
The user group was missing as a possible argument in the update_dataset method.
=> added user group as argument to update ds method

CHANGELOG.md, hari_client/client/client.py
https://quality-match.monday.com/boards/1606259534/pulses/1972102330
=> Add method to download media files from dataset

CHANGELOG.md, docs/example_code/quickstart_3D.py, hari_client/models/models.py
the class `PointCloudMetadata` contains a field `lidar_sensor_pose` which isn't usable was therefore removed.
=> align metadata with api

CHANGELOG.md, hari_client/models/models.py, hari_client/upload/hari_uploader.py, tests/test_hari_uploader.py
[Task](https://quality-match.monday.com/boards/1606259534/views/18393205/pulses/1919044423)
- Videos should allow no mediaObjects.
- Images only 2D mediaObjects.
- Pointclouds only 3D mediaObjects.
=> validate - media type compatible with mediaObject type

CHANGELOG.md, hari_client/client/client.py
[Task](https://quality-match.monday.com/boards/1606259534/pulses/2029064945)
=> Fix json encoding for nested pydantic models

CHANGELOG.md, hari_client/client/client.py, tests/test_client.py
https://quality-match.monday.com/boards/1606259534/pulses/1891324661
Prepare projection query param for request in the needed format
=> Prepare projection query param for request

CHANGELOG.md, hari_client/client/client.py
https://quality-match.monday.com/boards/1606259534/pulses/1891324661
Remove arguments for aint endpoints that were deleter from API models
=> Reflect api changes aints
